name: THC

# seq, gnn, fbnetgen 
type: dec_transformer
sizes: [90, 4]  # Note: The input node size should not be included here
pooling: [true, true]
pos_encoding: none  # identity, none
orthogonal: true
freeze_center: false
project_assignment: true
hierarchical: true
readout: concat
att_noise: false
clustering_type: learnable
mask_top_k: true

training:
  # normal or bilevel 
  method: normal
  lr: 1.0e-4
  weight_decay: 1.0e-5
  epochs: 200
  optimizer: adam

  group_loss: false
  sparsity_loss: false
  diff_loss: false
  dominate_loss: false
  clustering_loss: true
  dominate_loss_weight: 1.0e-4
  sparsity_loss_weight: 1.0e-4
  dominate_softmax: true
  log_folder: result
  assignment_loss: true
  topk: 3
  
  # uniform or pearson
  pure_gnn_graph: pearson